import React, { useState } from 'react';
import './PackingSuggestions.css';

/**
 * PackingSuggestions
 * ------------------
 * Displays categorised packing recommendations generated by
 * getPackingSuggestions(). Each category is expandable/collapsible.
 *
 * Props:
 *   suggestions {Array<{ category: string, emoji: string, items: string[] }>}
 */
function PackingSuggestions({ suggestions }) {
  // Track which categories are open. Default: all open.
  const [openCats, setOpenCats] = useState(() =>
    new Set(suggestions.map((s) => s.category))
  );

  const toggleCat = (cat) => {
    setOpenCats((prev) => {
      const next = new Set(prev);
      next.has(cat) ? next.delete(cat) : next.add(cat);
      return next;
    });
  };

  return (
    <div className="stp-card ps-card">
      <div className="stp-section-title">🎒 Smart Packing Assistant</div>

      <div className="ps-categories">
        {suggestions.map((group) => {
          const isOpen = openCats.has(group.category);
          return (
            <div key={group.category} className="ps-group">
              {/* Category header (clickable to collapse) */}
              <button
                className="ps-group-header"
                onClick={() => toggleCat(group.category)}
                aria-expanded={isOpen}
              >
                <span className="ps-group-emoji">{group.emoji}</span>
                <span className="ps-group-name">{group.category}</span>
                <span className="ps-group-count">{group.items.length} items</span>
                <span className="ps-chevron">{isOpen ? '▲' : '▼'}</span>
              </button>

              {/* Item list */}
              {isOpen && (
                <ul className="ps-item-list">
                  {group.items.map((item) => (
                    <li key={item} className="ps-item">
                      <span className="ps-dot" />
                      {item}
                    </li>
                  ))}
                </ul>
              )}
            </div>
          );
        })}
      </div>
    </div>
  );
}

export default PackingSuggestions;
